dependencies {
    api 'io.jsonwebtoken:jjwt-api:0.12.6'
    api 'org.springframework.security:spring-security-core'
    api 'org.springframework:spring-web'
    api 'org.springframework.boot:spring-boot-autoconfigure'
    api 'jakarta.servlet:jakarta.servlet-api'
    api 'org.slf4j:slf4j-api'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    testImplementation 'org.springframework:spring-test'
    testImplementation 'org.mockito:mockito-core'
    testRuntimeOnly 'ch.qos.logback:logback-classic'
}
