server:
  port: 8888

spring:
  application:
    name: config-server
  data:
    web:
      pageable:
        max-page-size: ${MAX_PAGE_SIZE:100}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
